# Introduction

Using this Python notebook you will:

1.  Understand three Chicago datasets
2.  Load the three datasets into three tables in a SQLIte database
3.  Execute SQL queries to answer assignment questions

## Understand the datasets

To complete the assignment problems in this notebook you will be using three datasets that are available on the city of Chicago's Data Portal:

1.  <a href="https://data.cityofchicago.org/Health-Human-Services/Census-Data-Selected-socioeconomic-indicators-in-C/kn9c-c2s2?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkDB0201ENSkillsNetwork20127838-2021-01-01">Socioeconomic Indicators in Chicago</a>
2.  <a href="https://data.cityofchicago.org/Education/Chicago-Public-Schools-Progress-Report-Cards-2011-/9xs2-f89t?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkDB0201ENSkillsNetwork20127838-2021-01-01">Chicago Public Schools</a>
3.  <a href="https://data.cityofchicago.org/Public-Safety/Crimes-2001-to-present/ijzp-q8t2?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkDB0201ENSkillsNetwork20127838-2021-01-01">Chicago Crime Data</a>

### 1. Socioeconomic Indicators in Chicago

This dataset contains a selection of six socioeconomic indicators of public health significance and a “hardship index,” for each Chicago community area, for the years 2008 – 2012.

A detailed description of this dataset and the original dataset can be obtained from the Chicago Data Portal at:

[https://data.cityofchicago.org/Health-Human-Services/Census-Data-Selected-socioeconomic-indicators-in-C/kn9c-c2s2](https://data.cityofchicago.org/Health-Human-Services/Census-Data-Selected-socioeconomic-indicators-in-C/kn9c-c2s2?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkDB0201ENSkillsNetwork20127838-2021-01-01&cm_mmc=Email_Newsletter-\_-Developer_Ed%2BTech-\_-WW_WW-\_-SkillsNetwork-Courses-IBMDeveloperSkillsNetwork-DB0201EN-SkillsNetwork-20127838&cm_mmca1=000026UJ&cm_mmca2=10006555&cm_mmca3=M12345678&cvosrc=email.Newsletter.M12345678&cvo_campaign=000026UJ)

### 2. Chicago Public Schools

This dataset shows all school level performance data used to create CPS School Report Cards for the 2011-2012 school year. This dataset is provided by the city of Chicago's Data Portal.

A detailed description of this dataset and the original dataset can be obtained from the Chicago Data Portal at:

[https://data.cityofchicago.org/Education/Chicago-Public-Schools-Progress-Report-Cards-2011-/9xs2-f89t](https://data.cityofchicago.org/Education/Chicago-Public-Schools-Progress-Report-Cards-2011-/9xs2-f89t?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkDB0201ENSkillsNetwork20127838-2021-01-01&cm_mmc=Email_Newsletter-\_-Developer_Ed%2BTech-\_-WW_WW-\_-SkillsNetwork-Courses-IBMDeveloperSkillsNetwork-DB0201EN-SkillsNetwork-20127838&cm_mmca1=000026UJ&cm_mmca2=10006555&cm_mmca3=M12345678&cvosrc=email.Newsletter.M12345678&cvo_campaign=000026UJ)

### 3. Chicago Crime Data

This dataset reflects reported incidents of crime (with the exception of murders where data exists for each victim) that occurred in the City of Chicago from 2001 to present, minus the most recent seven days.

A detailed description of this dataset and the original dataset can be obtained from the Chicago Data Portal at:

[https://data.cityofchicago.org/Public-Safety/Crimes-2001-to-present/ijzp-q8t2](https://data.cityofchicago.org/Public-Safety/Crimes-2001-to-present/ijzp-q8t2?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkDB0201ENSkillsNetwork20127838-2021-01-01&cm_mmc=Email_Newsletter-\_-Developer_Ed%2BTech-\_-WW_WW-\_-SkillsNetwork-Courses-IBMDeveloperSkillsNetwork-DB0201EN-SkillsNetwork-20127838&cm_mmca1=000026UJ&cm_mmca2=10006555&cm_mmca3=M12345678&cvosrc=email.Newsletter.M12345678&cvo_campaign=000026UJ)

### Download the datasets

This assignment requires you to have these three tables populated with a subset of the whole datasets.

In many cases the dataset to be analyzed is available as a .CSV (comma separated values) file, perhaps on the internet. 

Use the links below to read the data files using the Pandas library. 

* Chicago Census Data

https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DB0201EN-SkillsNetwork/labs/FinalModule_Coursera_V5/data/ChicagoCensusData.csv?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkDB0201ENSkillsNetwork20127838-2021-01-01

* Chicago Public Schools

https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DB0201EN-SkillsNetwork/labs/FinalModule_Coursera_V5/data/ChicagoPublicSchools.csv?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkDB0201ENSkillsNetwork20127838-2021-01-01

* Chicago Crime Data

https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DB0201EN-SkillsNetwork/labs/FinalModule_Coursera_V5/data/ChicagoCrimeData.csv?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkDB0201ENSkillsNetwork20127838-2021-01-01

**NOTE:** Ensure you use the datasets available on the links above instead of directly from the Chicago Data Portal. The versions linked here are subsets of the original datasets and have some of the column names modified to be more database friendly which will make it easier to complete this assignment.

### Store the datasets in database tables

To analyze the data using SQL, it first needs to be loaded into SQLite DB.
We will create three tables in as under:

1.  **CENSUS_DATA**
2.  **CHICAGO_PUBLIC_SCHOOLS**
3.  **CHICAGO_CRIME_DATA**

Load the `pandas` and `sqlite3` libraries and establish a connection to `FinalDB.db`

In [1]:
import csv, sqlite3 ,pandas

con = sqlite3.connect("FinalDB.db")
cur = con.cursor()

Load the SQL magic module

In [2]:
%load_ext sql
%config SqlMagic.displaylimit = None
%sql sqlite:///FinalDB.db

Deploy Shiny apps for free on Ploomber Cloud! Learn more: https://ploomber.io/s/signup

displaylimit: Value None will be treated as 0 (no limit)

Connecting to 'sqlite:///FinalDB.db'

Use `Pandas` to load the data available in the links above to dataframes. Use these dataframes to load data on to the database `FinalDB.db` as required tables.

In [3]:

df = pandas.read_csv('https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DB0201EN-SkillsNetwork/labs/FinalModule_Coursera_V5/data/ChicagoCensusData.csv?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkDB0201ENSkillsNetwork20127838-2021-01-01')
df.to_sql("CENSUS_DATA", con, if_exists='replace', index=False,method="multi")

78

In [4]:

df = pandas.read_csv('https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DB0201EN-SkillsNetwork/labs/FinalModule_Coursera_V5/data/ChicagoPublicSchools.csv')
df.to_sql("CHICAGO_PUBLIC_SCHOOLS_DATA", con, if_exists='replace', index=False,method="multi")

566

In [5]:

df = pandas.read_csv('https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DB0201EN-SkillsNetwork/labs/FinalModule_Coursera_V5/data/ChicagoCrimeData.csv?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkDB0201ENSkillsNetwork20127838-2021-01-01')
df.to_sql("CHICAGO_CRIME_DATA", con, if_exists='replace', index=False,method="multi")

533

Establish a connection between SQL magic module and the database `FinalDB.db`

In [6]:
%sql sqlite:///FinalDB.db

In [7]:
# type in your query to retrieve list of all tables in the database
%sql SELECT name FROM sqlite_master WHERE type='table'

Running query in 'sqlite:///FinalDB.db'

+-----------------------------+
|             name            |
+-----------------------------+
|         CENSUS_DATA         |
| CHICAGO_PUBLIC_SCHOOLS_DATA |
|      CHICAGO_CRIME_DATA     |
+-----------------------------+

In [8]:
# type in your query to retrieve all column names in the SCHOOLS table along with their datatypes and length
%sql SELECT name,type,length(type) FROM PRAGMA_TABLE_INFO('CHICAGO_CRIME_DATA');

Running query in 'sqlite:///FinalDB.db'

+-----------------------+---------+--------------+
|          name         |   type  | length(type) |
+-----------------------+---------+--------------+
|           ID          | INTEGER |      7       |
|      CASE_NUMBER      |   TEXT  |      4       |
|          DATE         |   TEXT  |      4       |
|         BLOCK         |   TEXT  |      4       |
|          IUCR         |   TEXT  |      4       |
|      PRIMARY_TYPE     |   TEXT  |      4       |
|      DESCRIPTION      |   TEXT  |      4       |
|  LOCATION_DESCRIPTION |   TEXT  |      4       |
|         ARREST        | INTEGER |      7       |
|        DOMESTIC       | INTEGER |      7       |
|          BEAT         | INTEGER |      7       |
|        DISTRICT       | INTEGER |      7       |
|          WARD         |   REAL  |      4       |
| COMMUNITY_AREA_NUMBER |   REAL  |      4       |
|        FBICODE        |   TEXT  |      4       |
|      X_COORDINATE     |   REAL  |      4       |
|      Y_COORDINATE     |   REAL  |      4       |
|          YEAR         | INTEGER |      7       |
|        LATITUDE       |   REAL  |      4       |
|       LONGITUDE       |   REAL  |      4       |
|        LOCATION       |   TEXT  |      4       |
+-----------------------+---------+--------------+

In [9]:
# type in your query to retrieve all column names in the SCHOOLS table along with their datatypes and length
%sql SELECT name,type,length(type) FROM PRAGMA_TABLE_INFO('CHICAGO_PUBLIC_SCHOOLS_DATA');

Running query in 'sqlite:///FinalDB.db'

+--------------------------------------------------+---------+--------------+
|                       name                       |   type  | length(type) |
+--------------------------------------------------+---------+--------------+
|                    School_ID                     | INTEGER |      7       |
|                  NAME_OF_SCHOOL                  |   TEXT  |      4       |
|        Elementary, Middle, or High School        |   TEXT  |      4       |
|                  Street_Address                  |   TEXT  |      4       |
|                       City                       |   TEXT  |      4       |
|                      State                       |   TEXT  |      4       |
|                     ZIP_Code                     | INTEGER |      7       |
|                   Phone_Number                   |   TEXT  |      4       |
|                       Link                       |   TEXT  |      4       |
|                 Network_Manager                  |   TEXT  |      4       |
|                Collaborative_Name                |   TEXT  |      4       |
|          Adequate_Yearly_Progress_Made_          |   TEXT  |      4       |
|                  Track_Schedule                  |   TEXT  |      4       |
|          CPS_Performance_Policy_Status           |   TEXT  |      4       |
|           CPS_Performance_Policy_Level           |   TEXT  |      4       |
|             HEALTHY_SCHOOL_CERTIFIED             |   TEXT  |      4       |
|                   Safety_Icon                    |   TEXT  |      4       |
|                   SAFETY_SCORE                   |   REAL  |      4       |
|             Family_Involvement_Icon              |   TEXT  |      4       |
|             Family_Involvement_Score             |   TEXT  |      4       |
|                 Environment_Icon                 |   TEXT  |      4       |
|                Environment_Score                 |   REAL  |      4       |
|                 Instruction_Icon                 |   TEXT  |      4       |
|                Instruction_Score                 |   REAL  |      4       |
|                   Leaders_Icon                   |   TEXT  |      4       |
|                  Leaders_Score                   |   TEXT  |      4       |
|                  Teachers_Icon                   |   TEXT  |      4       |
|                  Teachers_Score                  |   TEXT  |      4       |
|              Parent_Engagement_Icon              |   TEXT  |      4       |
|             Parent_Engagement_Score              |   TEXT  |      4       |
|             Parent_Environment_Icon              |   TEXT  |      4       |
|             Parent_Environment_Score             |   TEXT  |      4       |
|            AVERAGE_STUDENT_ATTENDANCE            |   TEXT  |      4       |
|      Rate_of_Misconducts__per_100_students_      |   REAL  |      4       |
|            Average_Teacher_Attendance            |   TEXT  |      4       |
| Individualized_Education_Program_Compliance_Rate |   TEXT  |      4       |
|                 Pk_2_Literacy__                  |   TEXT  |      4       |
|                   Pk_2_Math__                    |   TEXT  |      4       |
|             Gr3_5_Grade_Level_Math__             |   TEXT  |      4       |
|             Gr3_5_Grade_Level_Read__             |   TEXT  |      4       |
|              Gr3_5_Keep_Pace_Read__              |   TEXT  |      4       |
|              Gr3_5_Keep_Pace_Math__              |   TEXT  |      4       |
|             Gr6_8_Grade_Level_Math__             |   TEXT  |      4       |
|             Gr6_8_Grade_Level_Read__             |   TEXT  |      4       |
|              Gr6_8_Keep_Pace_Math_               |   TEXT  |      4       |
|              Gr6_8_Keep_Pace_Read__              |   TEXT  |      4       |
|               Gr_8_Explore_Math__                |   TEXT  |      4       |
|               Gr_8_Explore_Read__                |   TEXT  |      4       |
|              ISAT_Exceeding_Math__               |   REAL  |      4       |
|             ISAT_Exceeding_Reading__             |   REAL  |      4       |
|               ISAT_Value_Add_Math                |   REAL  |      4       |
|               ISAT_Value_Add_Read                |   REAL  |      4       |
|            ISAT_Value_Add_Color_Math             |   TEXT  |      4       |
|            ISAT_Value_Add_Color_Read             |   TEXT  |      4       |
|            Students_Taking__Algebra__            |   TEXT  |      4       |
|           Students_Passing__Algebra__            |   TEXT  |      4       |
|             9th Grade EXPLORE (2009)             |   TEXT  |      4       |
|             9th Grade EXPLORE (2010)             |   TEXT  |      4       |
|              10th Grade PLAN (2009)              |   TEXT  |      4       |
|              10th Grade PLAN (2010)              |   TEXT  |      4       |
|           Net_Change_EXPLORE_and_PLAN            |   TEXT  |      4       |
|          11th Grade Average ACT (2011)           |   TEXT  |      4       |
|             Net_Change_PLAN_and_ACT              |   TEXT  |      4       |
|              College_Eligibility__               |   TEXT  |      4       |
|                Graduation_Rate__                 |   TEXT  |      4       |
|            College_Enrollment_Rate__             |   TEXT  |      4       |
|                COLLEGE_ENROLLMENT                | INTEGER |      7       |
|              General_Services_Route              | INTEGER |      7       |
|             Freshman_on_Track_Rate__             |   TEXT  |      4       |
|                   X_COORDINATE                   |   REAL  |      4       |
|                   Y_COORDINATE                   |   REAL  |      4       |
|                     Latitude                     |   REAL  |      4       |
|                    Longitude                     |   REAL  |      4       |
|              COMMUNITY_AREA_NUMBER               | INTEGER |      7       |
|               COMMUNITY_AREA_NAME                |   TEXT  |      4       |
|                       Ward                       | INTEGER |      7       |
|                 Police_District                  | INTEGER |      7       |
|                     Location                     |   TEXT  |      4       |
+--------------------------------------------------+---------+--------------+

In [10]:
# type in your query to retrieve all column names in the SCHOOLS table along with their datatypes and length
%sql SELECT name,type,length(type) FROM PRAGMA_TABLE_INFO('CENSUS_DATA');

Running query in 'sqlite:///FinalDB.db'

+----------------------------------------------+---------+--------------+
|                     name                     |   type  | length(type) |
+----------------------------------------------+---------+--------------+
|            COMMUNITY_AREA_NUMBER             |   REAL  |      4       |
|             COMMUNITY_AREA_NAME              |   TEXT  |      4       |
|          PERCENT_OF_HOUSING_CROWDED          |   REAL  |      4       |
|       PERCENT_HOUSEHOLDS_BELOW_POVERTY       |   REAL  |      4       |
|         PERCENT_AGED_16__UNEMPLOYED          |   REAL  |      4       |
| PERCENT_AGED_25__WITHOUT_HIGH_SCHOOL_DIPLOMA |   REAL  |      4       |
|       PERCENT_AGED_UNDER_18_OR_OVER_64       |   REAL  |      4       |
|              PER_CAPITA_INCOME               | INTEGER |      7       |
|                HARDSHIP_INDEX                |   REAL  |      4       |
+----------------------------------------------+---------+--------------+

You can now proceed to the the following questions. Please note that a graded assignment will follow this lab and there will be a question on each of the problems stated below. It can be from the answer you received or the code you write for this problem. Therefore, please keep a note of both your codes as well as the response you generate.

## Problems

Now write and execute SQL queries to solve assignment problems

### Problem 1

##### Find the total number of crimes recorded in the CRIME table.

In [11]:
%%sql
Select count(ID) as NumberOfCrimes from CHICAGO_CRIME_DATA

Running query in 'sqlite:///FinalDB.db'

+----------------+
| NumberOfCrimes |
+----------------+
|      533       |
+----------------+

### Problem 2

##### List community area names and numbers with per capita income less than 11000.

In [12]:
%%sql
Select COMMUNITY_AREA_NAME ,COMMUNITY_AREA_NUMBER,PER_CAPITA_INCOME  from CENSUS_DATA
where PER_CAPITA_INCOME < 11000

Running query in 'sqlite:///FinalDB.db'

+---------------------+-----------------------+-------------------+
| COMMUNITY_AREA_NAME | COMMUNITY_AREA_NUMBER | PER_CAPITA_INCOME |
+---------------------+-----------------------+-------------------+
|  West Garfield Park |          26.0         |       10934       |
|    South Lawndale   |          30.0         |       10402       |
|     Fuller Park     |          37.0         |       10432       |
|      Riverdale      |          54.0         |        8201       |
+---------------------+-----------------------+-------------------+

### Problem 3

##### List all case numbers for crimes involving minors?(children are not considered minors for the purposes of crime analysis)

In [13]:
%%sql
Select ID , CASE_NUMBER , PRIMARY_TYPE	, DESCRIPTION	from CHICAGO_CRIME_DATA
where `DESCRIPTION`	like '%Minor%'

Running query in 'sqlite:///FinalDB.db'

+---------+-------------+----------------------+-------------------------------+
|    ID   | CASE_NUMBER |     PRIMARY_TYPE     |          DESCRIPTION          |
+---------+-------------+----------------------+-------------------------------+
| 3987219 |   HL266884  | LIQUOR LAW VIOLATION | SELL/GIVE/DEL LIQUOR TO MINOR |
| 3266814 |   HK238408  | LIQUOR LAW VIOLATION |  ILLEGAL CONSUMPTION BY MINOR |
+---------+-------------+----------------------+-------------------------------+

### Problem 4

##### List all kidnapping crimes involving a child?

In [14]:
%%sql
Select ID , CASE_NUMBER , PRIMARY_TYPE	, DESCRIPTION	from CHICAGO_CRIME_DATA
where PRIMARY_TYPE = "KIDNAPPING" AND `DESCRIPTION`	like '%Child%'

Running query in 'sqlite:///FinalDB.db'

+---------+-------------+--------------+--------------------------+
|    ID   | CASE_NUMBER | PRIMARY_TYPE |       DESCRIPTION        |
+---------+-------------+--------------+--------------------------+
| 5276766 |   HN144152  |  KIDNAPPING  | CHILD ABDUCTION/STRANGER |
+---------+-------------+--------------+--------------------------+

### Problem 5

##### List the kind of crimes that were recorded at schools. (No repetitions)

In [15]:
%%sql
Select DISTINCT ID , CASE_NUMBER , PRIMARY_TYPE	, DESCRIPTION	from CHICAGO_CRIME_DATA
where  `LOCATION_DESCRIPTION` like '%School%'

Running query in 'sqlite:///FinalDB.db'

+----------+-------------+------------------------+--------------------------------+
|    ID    | CASE_NUMBER |      PRIMARY_TYPE      |          DESCRIPTION           |
+----------+-------------+------------------------+--------------------------------+
| 4006321  |   HL353697  |        BATTERY         |             SIMPLE             |
| 4430638  |   HL725506  |        BATTERY         |  PRO EMP HANDS NO/MIN INJURY   |
| 6644618  |   HP716225  |        BATTERY         |             SIMPLE             |
| 2341955  |   HH639427  |        BATTERY         |             SIMPLE             |
| 11110571 |   JA460432  |        BATTERY         |             SIMPLE             |
| 7399281  |   HS200939  |    CRIMINAL DAMAGE     |           TO VEHICLE           |
| 3530721  |   HK577020  |       NARCOTICS        |      POSS: HEROIN(WHITE)       |
| 7502426  |   HS305355  |       NARCOTICS        | MANU/DEL:CANNABIS 10GM OR LESS |
| 8082600  |   HT315369  |        ASSAULT         |  PRO EMP HANDS NO/MIN INJURY   |
| 7174283  |   HR585012  |   CRIMINAL TRESPASS    |            TO LAND             |
| 2075734  |   HH292682  | PUBLIC PEACE VIOLATION |          BOMB THREAT           |
| 1806896  |   G635735   | PUBLIC PEACE VIOLATION |          BOMB THREAT           |
+----------+-------------+------------------------+--------------------------------+

### Problem 6

##### List the type of schools along with the average safety score for each type.

In [16]:
%%sql
select `Elementary, Middle, or High School`as TypeOfSchool  ,avg(SAFETY_SCORE) as AverageSafetyScore  from CHICAGO_PUBLIC_SCHOOLS_DATA
group by `Elementary, Middle, or High School`

Running query in 'sqlite:///FinalDB.db'

+--------------+--------------------+
| TypeOfSchool | AverageSafetyScore |
+--------------+--------------------+
|      ES      | 49.52038369304557  |
|      HS      | 49.62352941176471  |
|      MS      |        48.0        |
+--------------+--------------------+

### Problem 7

##### List 5 community areas with highest % of households below poverty line

In [17]:
%%sql
select COMMUNITY_AREA_NAME , COMMUNITY_AREA_NUMBER ,PERCENT_HOUSEHOLDS_BELOW_POVERTY from CENSUS_DATA
order by PERCENT_HOUSEHOLDS_BELOW_POVERTY desc limit 5

Running query in 'sqlite:///FinalDB.db'

+---------------------+-----------------------+----------------------------------+
| COMMUNITY_AREA_NAME | COMMUNITY_AREA_NUMBER | PERCENT_HOUSEHOLDS_BELOW_POVERTY |
+---------------------+-----------------------+----------------------------------+
|      Riverdale      |          54.0         |               56.5               |
|     Fuller Park     |          37.0         |               51.2               |
|      Englewood      |          68.0         |               46.6               |
|    North Lawndale   |          29.0         |               43.1               |
|  East Garfield Park |          27.0         |               42.4               |
+---------------------+-----------------------+----------------------------------+

### Problem 8

##### Which community area is most crime prone? Display the coumminty area number only.

In [24]:
%%sql
SELECT COMMUNITY_AREA_NUMBER 
FROM (SELECT COMMUNITY_AREA_NUMBER, COUNT(*) AS crime_count 
FROM CHICAGO_CRIME_DATA 
GROUP BY COMMUNITY_AREA_NUMBER 
ORDER BY crime_count DESC LIMIT 1)

Running query in 'sqlite:///FinalDB.db'

+-----------------------+
| COMMUNITY_AREA_NUMBER |
+-----------------------+
|          25.0         |
+-----------------------+


Double-click **here** for a hint

<!--
Query for the 'community area number' that has most number of incidents
-->

### Problem 9

##### Use a sub-query to find the name of the community area with highest hardship index

In [ ]:
%%sql
SELECT COMMUNITY_AREA_NAME FROM CENSUS_DATA
WHERE HARDSHIP_INDEX = (SELECT MAX(HARDSHIP_INDEX) FROM CENSUS_DATA)

Running query in 'sqlite:///FinalDB.db'

+---------------------+
| COMMUNITY_AREA_NAME |
+---------------------+
|      Riverdale      |
+---------------------+

### Problem 10

##### Use a sub-query to determine the Community Area Name with most number of crimes?

In [23]:
%%sql
SELECT COMMUNITY_AREA_NAME
FROM CENSUS_DATA
WHERE COMMUNITY_AREA_NUMBER = (
SELECT COMMUNITY_AREA_NUMBER
FROM (SELECT COMMUNITY_AREA_NUMBER, COUNT(*) AS crime_count FROM CHICAGO_CRIME_DATA GROUP BY COMMUNITY_AREA_NUMBER 
ORDER BY crime_count DESC LIMIT 1))

Running query in 'sqlite:///FinalDB.db'

+---------------------+
| COMMUNITY_AREA_NAME |
+---------------------+
|        Austin       |
+---------------------+